### ISSUE TITLE
Unblocking captcha not displaying

### ISSUE THREAD

**Issue by gustavdelius** [beloglazov/zotero-scholar-citations#12]
Since upgrading to version 1.9 in my zotero stand-alone and trying to update the citations for a large bunch of papers yesterday morning I have been blocked by Google. Since then each time I edit an item in Zotero, I get a pop-up telling me about a captcha, but no captcha is displayed. When I used Google scholar directly from my browser (Chrome) the captcha was displayed and I was cleared to use Google scholar in the browser, but I still get the pop-ups in Zotero. Is there perhaps a problem with the captcha pop-ups in Zotero standalone?

**Comment by beloglazov** [comment]
That was actually a bug, which I've just fixed in 1.9.1. Thanks for letting me know!

**Comment by BenjaminHCCarr** [comment]
Ah, Sorry, I missed the merge comment. Thanks. I am having Captcha problems on Standalone on WIn7 and OSX so I thought you might have found a solution.

**Comment by rainmisty** [comment]
* have updated to 1.9.1 for standalone, but it still can't open Captcha window.  Any solution? Thanks in advance!

**Comment by BenjaminHCCarr** [comment]
@rainmisty I have not found a way around this sadly; it's a google scholar rate-limiting issue.
Two extra problems:
1) Many scientists behind one IP (NAT)
2) It block ALL of Google Scholar if you trip the limit (and the limit can be days long bans)
